language: python
python:
#can't do too many b/c will hit Spark rate limiter
    - "2.7"

# command to install dependencies
install:
    - pip install -e . python-coveralls

script:
    - python setup.py nosetests

after_success:
    - coveralls